environment:
  TOOLSET: vs2017

configuration: Release

platform: Any CPU

before_build: 
  - nuget restore
  - ps: . .\vsix.ps1
  - ps: Vsix-ChangeBuildNumber

build:
  project: VS-QuickNavigation.sln
  verbosity: minimal
